Default: &defaults
  database: frt.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: frt_test.sqlite3
  <<: *defaults

Staging:
  database: frt_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: frt_production.sqlite3
  poolsize: 100
  <<: *defaults
